/**
 * Eks-Health Competition Platform — Prize Pools
 *
 * The platform manages prize pool accounting ONLY. It does NOT execute
 * payments. Prize pools receive funding from events generated by the Payment
 * Provider (measurement ticket allocations, program treasury, sponsors,
 * employers, governments, insurance providers, developer contributions,
 * donations, platform incentives).
 *
 * Funding flows:
 *  - credit(): adds funds (records a transaction, updates balance). When the
 *    source is `measurement_ticket_allocation`, emits `prize_pool.fee_received`.
 *  - debit(): removes funds (for reward distributions). Records a transaction.
 *  - allocate(): earmarks funds for a participant (pending → allocated).
 *  - markPaid(): the payment provider confirmed the payout (allocated → paid).
 *  - cancelAllocation(): releases earmarked funds back to available.
 *
 * Real double-entry-style accounting:
 *   balance   = Σ credits − Σ debits
 *   allocated = Σ allocations in `allocated` status
 *   pending   = Σ allocations in `pending` status
 *   available = balance − allocated − pending
 */

import "server-only";
import {
  type PrizePoolId,
  type PrizeAllocationId,
  type CompetitionId,
  type SeasonId,
  type AccountId,
  type PrizePoolEntry,
  type PrizePoolFundingSource,
  type RewardScheduleId,
  CompetitionError,
  asPrizePoolId,
  asPrizeAllocationId,
} from "../core";
import { getEventBus, buildEvent, generateId, getClock } from "@/kernel";
import { COMPETITION_EVENTS } from "../core";

// ---------------------------------------------------------------------------
// Transaction & allocation records
// ---------------------------------------------------------------------------

export interface PrizePoolTransaction {
  readonly id: string;
  readonly poolId: PrizePoolId;
  readonly type: "credit" | "debit";
  readonly source: PrizePoolFundingSource;
  readonly amount: number;
  readonly currency: string;
  readonly reference?: string;
  readonly at: string;
  readonly description?: string;
}

export type PrizeAllocationStatus = "pending" | "allocated" | "paid" | "cancelled";

export interface PrizeAllocation {
  readonly id: PrizeAllocationId;
  readonly poolId: PrizePoolId;
  readonly participantId: AccountId;
  readonly amount: number;
  readonly scheduleId?: RewardScheduleId;
  readonly status: PrizeAllocationStatus;
  readonly at: string;
  readonly paidAt?: string;
  readonly cancelledAt?: string;
  readonly cancelReason?: string;
}

/** A prize pool is the public PrizePoolEntry shape from core. */
export type PrizePool = PrizePoolEntry;

export interface PrizePoolBalance {
  readonly balance: number;
  readonly allocated: number;
  readonly pending: number;
  readonly available: number;
  readonly paid: number;
}

export interface PrizePoolStats {
  readonly totalPools: number;
  readonly totalBalance: number;
  readonly totalAllocated: number;
  readonly totalPaid: number;
  readonly totalAvailable: number;
  readonly byCurrency: Record<string, number>;
}

// ---------------------------------------------------------------------------
// Prize pool manager
// ---------------------------------------------------------------------------

export class PrizePoolManager {
  private readonly pools = new Map<PrizePoolId, PrizePool>();
  private readonly transactions = new Map<PrizePoolId, PrizePoolTransaction[]>();
  private readonly allocations = new Map<PrizePoolId, PrizeAllocation[]>();
  private readonly allocationById = new Map<PrizeAllocationId, PrizeAllocation>();
  private readonly byCompetition = new Map<CompetitionId, PrizePoolId[]>();

  create(competitionId: CompetitionId, seasonId: SeasonId, currency: string): PrizePool {
    if (!currency || currency.length !== 3) {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.invalid_currency",
        category: "validation",
        message: `Currency must be a 3-letter ISO-4217 code (got '${currency}').`,
        userMessage: "A valid 3-letter currency code is required.",
      });
    }
    const now = getClock().iso();
    const pool: PrizePool = {
      id: asPrizePoolId(generateId("pool_")),
      competitionId,
      seasonId,
      currency: currency.toUpperCase(),
      balance: 0,
      allocated: 0,
      pending: 0,
      fundingSources: [],
      createdAt: now,
      updatedAt: now,
    };
    this.pools.set(pool.id, pool);
    this.transactions.set(pool.id, []);
    this.allocations.set(pool.id, []);
    const list = this.byCompetition.get(competitionId) ?? [];
    this.byCompetition.set(competitionId, [...list, pool.id]);
    void getEventBus().publish(
      buildEvent(
        COMPETITION_EVENTS.prizePoolUpdated,
        { poolId: pool.id, competitionId, seasonId, currency: pool.currency, action: "created", balance: 0 },
        {},
        "domain",
      ),
    );
    return pool;
  }

  get(id: PrizePoolId): PrizePool | undefined {
    return this.pools.get(id);
  }

  list(competitionId?: CompetitionId, seasonId?: SeasonId): PrizePool[] {
    let list = [...this.pools.values()];
    if (competitionId) list = list.filter((p) => p.competitionId === competitionId);
    if (seasonId) list = list.filter((p) => p.seasonId === seasonId);
    return list;
  }

  listByCompetition(competitionId: CompetitionId): PrizePool[] {
    return (this.byCompetition.get(competitionId) ?? []).map((id) => this.pools.get(id)!).filter(Boolean);
  }

  /**
   * Add funds to a prize pool. Records a credit transaction, updates the
   * balance, and appends to the funding-sources ledger. When the source is
   * `measurement_ticket_allocation`, also emits `prize_pool.fee_received`.
   */
  credit(
    poolId: PrizePoolId,
    source: PrizePoolFundingSource,
    amount: number,
    reference?: string,
    description?: string,
  ): PrizePoolTransaction {
    const pool = this.pools.get(poolId);
    if (!pool) {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.not_found",
        category: "not_found",
        message: `Prize pool ${poolId} not found.`,
      });
    }
    if (!(amount > 0) || !Number.isFinite(amount)) {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.invalid_amount",
        category: "validation",
        message: `Credit amount must be a positive finite number (got ${amount}).`,
      });
    }
    const now = getClock().iso();
    const txn: PrizePoolTransaction = {
      id: generateId("txn_"),
      poolId,
      type: "credit",
      source,
      amount,
      currency: pool.currency,
      reference,
      at: now,
      description,
    };
    const txns = this.transactions.get(poolId) ?? [];
    this.transactions.set(poolId, [...txns, txn]);
    const newBalance = pool.balance + amount;
    const fundingSources = [...pool.fundingSources, { source, amount, reference, at: now }];
    this.pools.set(poolId, { ...pool, balance: newBalance, fundingSources, updatedAt: now });
    void getEventBus().publish(
      buildEvent(
        COMPETITION_EVENTS.prizePoolUpdated,
        { poolId, competitionId: pool.competitionId, seasonId: pool.seasonId, action: "credit", source, amount, balance: newBalance, reference },
        {},
        "domain",
      ),
    );
    if (source === "measurement_ticket_allocation") {
      void getEventBus().publish(
        buildEvent(
          COMPETITION_EVENTS.measurementFeeReceived,
          { poolId, competitionId: pool.competitionId, seasonId: pool.seasonId, amount, currency: pool.currency, reference },
          {},
          "domain",
        ),
      );
    }
    return txn;
  }

  /**
   * Remove funds from a prize pool (used for reward distributions). Records a
   * debit transaction and updates the balance. The payment provider is
   * responsible for the actual money movement — this is accounting only.
   */
  debit(poolId: PrizePoolId, amount: number, reference?: string, description?: string): PrizePoolTransaction {
    const pool = this.pools.get(poolId);
    if (!pool) {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.not_found",
        category: "not_found",
        message: `Prize pool ${poolId} not found.`,
      });
    }
    if (!(amount > 0) || !Number.isFinite(amount)) {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.invalid_amount",
        category: "validation",
        message: `Debit amount must be a positive finite number (got ${amount}).`,
      });
    }
    const now = getClock().iso();
    const txn: PrizePoolTransaction = {
      id: generateId("txn_"),
      poolId,
      type: "debit",
      source: "program_treasury",
      amount,
      currency: pool.currency,
      reference,
      at: now,
      description: description ?? "reward distribution",
    };
    const txns = this.transactions.get(poolId) ?? [];
    this.transactions.set(poolId, [...txns, txn]);
    const newBalance = pool.balance - amount;
    this.pools.set(poolId, { ...pool, balance: newBalance, updatedAt: now });
    void getEventBus().publish(
      buildEvent(
        COMPETITION_EVENTS.prizePoolUpdated,
        { poolId, competitionId: pool.competitionId, seasonId: pool.seasonId, action: "debit", amount, balance: newBalance, reference },
        {},
        "domain",
      ),
    );
    return txn;
  }

  /**
   * Earmark funds for a participant. Creates a PrizeAllocation in the
   * `allocated` status (pending → allocated transition). Tracks the allocated
   * total on the pool entry.
   */
  allocate(
    poolId: PrizePoolId,
    participantId: AccountId,
    amount: number,
    scheduleId?: RewardScheduleId,
  ): PrizeAllocation {
    const pool = this.pools.get(poolId);
    if (!pool) {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.not_found",
        category: "not_found",
        message: `Prize pool ${poolId} not found.`,
      });
    }
    if (!(amount > 0) || !Number.isFinite(amount)) {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.invalid_amount",
        category: "validation",
        message: `Allocation amount must be a positive finite number (got ${amount}).`,
      });
    }
    const bal = this.computeBalance(poolId, pool);
    if (amount > bal.available) {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.insufficient_funds",
        category: "state_conflict",
        message: `Cannot allocate ${amount}: available balance is ${bal.available} ${pool.currency}.`,
        userMessage: "The prize pool does not have enough available funds for this allocation.",
        metadata: { poolId, requested: amount, available: bal.available },
      });
    }
    const now = getClock().iso();
    const alloc: PrizeAllocation = {
      id: asPrizeAllocationId(generateId("alloc_")),
      poolId,
      participantId,
      amount,
      scheduleId,
      status: "allocated",
      at: now,
    };
    const list = this.allocations.get(poolId) ?? [];
    this.allocations.set(poolId, [...list, alloc]);
    this.allocationById.set(alloc.id, alloc);
    const newAllocated = pool.allocated + amount;
    this.pools.set(poolId, { ...pool, allocated: newAllocated, updatedAt: now });
    return alloc;
  }

  /**
   * Mark an allocation as paid — the payment provider has confirmed the
   * transfer. Does NOT execute payment; only records the confirmation.
   * Transitions the allocation from `allocated` → `paid` and releases the
   * earmarked amount from the pool's `allocated` counter.
   */
  markPaid(allocationId: PrizeAllocationId): PrizeAllocation {
    const alloc = this.allocationById.get(allocationId);
    if (!alloc) {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.allocation.not_found",
        category: "not_found",
        message: `Allocation ${allocationId} not found.`,
      });
    }
    if (alloc.status !== "allocated") {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.allocation.invalid_state",
        category: "state_conflict",
        message: `Cannot mark allocation as paid from status '${alloc.status}'.`,
        userMessage: "This allocation cannot be marked as paid in its current state.",
        metadata: { allocationId, currentStatus: alloc.status },
      });
    }
    const now = getClock().iso();
    const updated: PrizeAllocation = { ...alloc, status: "paid", paidAt: now };
    this.allocationById.set(allocationId, updated);
    const list = this.allocations.get(alloc.poolId) ?? [];
    this.allocations.set(alloc.poolId, list.map((a) => (a.id === allocationId ? updated : a)));
    const pool = this.pools.get(alloc.poolId);
    if (pool) {
      const newAllocated = Math.max(0, pool.allocated - alloc.amount);
      this.pools.set(alloc.poolId, { ...pool, allocated: newAllocated, updatedAt: now });
    }
    return updated;
  }

  cancelAllocation(allocationId: PrizeAllocationId, reason: string): PrizeAllocation {
    const alloc = this.allocationById.get(allocationId);
    if (!alloc) {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.allocation.not_found",
        category: "not_found",
        message: `Allocation ${allocationId} not found.`,
      });
    }
    if (alloc.status === "paid" || alloc.status === "cancelled") {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.allocation.invalid_state",
        category: "state_conflict",
        message: `Cannot cancel allocation in status '${alloc.status}'.`,
        metadata: { allocationId, currentStatus: alloc.status },
      });
    }
    const now = getClock().iso();
    const updated: PrizeAllocation = { ...alloc, status: "cancelled", cancelledAt: now, cancelReason: reason };
    this.allocationById.set(allocationId, updated);
    const list = this.allocations.get(alloc.poolId) ?? [];
    this.allocations.set(alloc.poolId, list.map((a) => (a.id === allocationId ? updated : a)));
    // Release the earmarked amount back to available.
    const pool = this.pools.get(alloc.poolId);
    if (pool && alloc.status === "allocated") {
      const newAllocated = Math.max(0, pool.allocated - alloc.amount);
      this.pools.set(alloc.poolId, { ...pool, allocated: newAllocated, updatedAt: now });
    }
    return updated;
  }

  getAllocation(id: PrizeAllocationId): PrizeAllocation | undefined {
    return this.allocationById.get(id);
  }

  /** Compute the live balance from transactions + allocations (double-entry). */
  private computeBalance(poolId: PrizePoolId, pool: PrizePool): PrizePoolBalance {
    const txns = this.transactions.get(poolId) ?? [];
    const credits = txns.filter((t) => t.type === "credit").reduce((s, t) => s + t.amount, 0);
    const debits = txns.filter((t) => t.type === "debit").reduce((s, t) => s + t.amount, 0);
    const computedBalance = credits - debits;
    const allocs = this.allocations.get(poolId) ?? [];
    const allocated = allocs.filter((a) => a.status === "allocated").reduce((s, a) => s + a.amount, 0);
    const pending = allocs.filter((a) => a.status === "pending").reduce((s, a) => s + a.amount, 0);
    const paid = allocs.filter((a) => a.status === "paid").reduce((s, a) => s + a.amount, 0);
    // Use the transaction-derived balance as the source of truth; fall back to
    // the cached pool.balance if no transactions exist yet (defensive).
    const balance = txns.length > 0 ? computedBalance : pool.balance;
    return { balance, allocated, pending, available: balance - allocated - pending, paid };
  }

  getBalance(poolId: PrizePoolId): PrizePoolBalance {
    const pool = this.pools.get(poolId);
    if (!pool) {
      throw new CompetitionError({
        code: "eks.competition.prize_pool.not_found",
        category: "not_found",
        message: `Prize pool ${poolId} not found.`,
      });
    }
    return this.computeBalance(poolId, pool);
  }

  getTransactions(poolId: PrizePoolId): readonly PrizePoolTransaction[] {
    return this.transactions.get(poolId) ?? [];
  }

  getAllocations(
    poolId: PrizePoolId,
    filter?: { participantId?: AccountId; status?: PrizeAllocationStatus; scheduleId?: RewardScheduleId },
  ): readonly PrizeAllocation[] {
    let list = this.allocations.get(poolId) ?? [];
    if (filter?.participantId) list = list.filter((a) => a.participantId === filter.participantId);
    if (filter?.status) list = list.filter((a) => a.status === filter.status);
    if (filter?.scheduleId) list = list.filter((a) => a.scheduleId === filter.scheduleId);
    return list;
  }

  getStats(competitionId?: CompetitionId): PrizePoolStats {
    let pools = [...this.pools.values()];
    if (competitionId) pools = pools.filter((p) => p.competitionId === competitionId);
    const byCurrency: Record<string, number> = {};
    let totalBalance = 0;
    let totalAllocated = 0;
    let totalPaid = 0;
    let totalAvailable = 0;
    for (const p of pools) {
      const bal = this.computeBalance(p.id, p);
      totalBalance += bal.balance;
      totalAllocated += bal.allocated;
      totalPaid += bal.paid;
      totalAvailable += bal.available;
      byCurrency[p.currency] = (byCurrency[p.currency] ?? 0) + bal.balance;
    }
    return { totalPools: pools.length, totalBalance, totalAllocated, totalPaid, totalAvailable, byCurrency };
  }
}

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------

let _mgr: PrizePoolManager | null = null;
export function getPrizePools(): PrizePoolManager {
  if (!_mgr) _mgr = new PrizePoolManager();
  return _mgr;
}

export function resetPrizePools(): void {
  _mgr = null;
}
