"use client";

import { Coins, TrendingUp, Gift, AlertCircle } from "lucide-react";
import { SectionHeader, Panel, Mono, StatCard, EmptyState } from "../primitives";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import type { PlatformSnapshot } from "@/hooks/use-platform";

export function PrizePoolsSection({ data }: { data: PlatformSnapshot }) {
  const comps = (data.competitions as {
    prizePools?: Array<{ id: string; competitionId: string; currency: string; balance: number; allocated: number; pending: number }>;
    rewardEvents?: Array<{ id: string; type: string; participantId: string; rank: number; amount: number; currency: string; createdAt: string }>;
    rewardSchedules?: Array<{ id: string; name: string; type: string; podiumSize: number; distribution?: Array<{ rank: number; percentage: number }> }>;
  }) ?? {};
  const pools = comps.prizePools ?? [];
  const rewardEvents = comps.rewardEvents ?? [];
  const schedules = comps.rewardSchedules ?? [];

  const totalBalance = pools.reduce((a, p) => a + p.balance, 0);
  const totalAllocated = pools.reduce((a, p) => a + p.allocated, 0);
  const totalPending = pools.reduce((a, p) => a + p.pending, 0);
  const totalRewards = rewardEvents.filter((e) => e.type === "reward_triggered" || e.type === "reward_ready").reduce((a, e) => a + e.amount, 0);

  const fundingSources = [
    "measurement_ticket_allocation", "program_treasury", "sponsors", "employers",
    "governments", "insurance_providers", "developer_contributions", "donations", "platform_incentives",
  ];

  return (
    <div className="space-y-6">
      <SectionHeader
        title="Prize Pools & Rewards"
        subtitle="The platform manages prize pool accounting ONLY — it does NOT execute payments. Prize pools receive funding from events generated by the Payment Provider. The Competition Engine records balances and allocations but delegates financial execution to PaySwap (or any provider)."
        icon={<Coins className="h-5 w-5" />}
      />

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <StatCard label="Total Balance" value={`$${totalBalance.toLocaleString()}`} accent />
        <StatCard label="Allocated" value={`$${totalAllocated.toLocaleString()}`} />
        <StatCard label="Pending" value={`$${totalPending.toLocaleString()}`} />
        <StatCard label="Rewards Triggered" value={`$${totalRewards.toLocaleString()}`} />
      </div>

      <Panel title="Prize Pools">
        {pools.length === 0 ? <EmptyState message="No prize pools yet. Create a competition to initialize one." /> : (
          <div className="max-h-[24rem] overflow-y-auto eks-scroll -mx-2">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="pl-4">Pool</TableHead>
                  <TableHead>Currency</TableHead>
                  <TableHead>Balance</TableHead>
                  <TableHead>Allocated</TableHead>
                  <TableHead>Pending</TableHead>
                  <TableHead className="pr-4">Available</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {pools.map((p) => (
                  <TableRow key={p.id}>
                    <TableCell className="pl-4"><Mono className="text-xs">{p.id.slice(0, 20)}…</Mono></TableCell>
                    <TableCell><Mono className="text-xs">{p.currency}</Mono></TableCell>
                    <TableCell><span className="text-xs font-medium text-[var(--brand)]">{p.currency} {p.balance.toLocaleString()}</span></TableCell>
                    <TableCell><Mono className="text-xs">{p.allocated.toLocaleString()}</Mono></TableCell>
                    <TableCell><Mono className="text-xs text-amber-500">{p.pending.toLocaleString()}</Mono></TableCell>
                    <TableCell className="pr-4"><Mono className="text-xs text-[var(--brand)]">{(p.balance - p.allocated).toLocaleString()}</Mono></TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
      </Panel>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <Panel title="Funding Sources">
          <p className="text-xs text-muted-foreground mb-2">Prize pools receive funding from multiple sources via Payment Provider events:</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5">
            {fundingSources.map((s) => (
              <div key={s} className="flex items-center gap-1.5 text-xs rounded-md border border-border/40 p-2">
                <TrendingUp className="h-3 w-3 text-[var(--brand)]" />
                <Mono className="text-[10px]">{s}</Mono>
              </div>
            ))}
          </div>
        </Panel>

        <Panel title="Reward Schedules">
          {schedules.length === 0 ? <EmptyState message="No reward schedules." /> : (
            <div className="space-y-2">
              {schedules.map((s) => (
                <div key={s.id} className="rounded-md border border-border/60 p-2.5">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium">{s.name}</span>
                    <div className="flex items-center gap-1">
                      <Badge variant="outline" className="text-[10px]">{s.type}</Badge>
                      <Badge variant="secondary" className="text-[10px]">podium: {s.podiumSize}</Badge>
                    </div>
                  </div>
                  {s.distribution && (
                    <div className="flex items-center gap-1 mt-2">
                      {s.distribution.map((d) => (
                        <div key={d.rank} className="flex-1 text-center">
                          <div className="text-[10px] text-muted-foreground">#{d.rank}</div>
                          <div className="text-xs font-mono text-[var(--brand)]">{d.percentage}%</div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </Panel>
      </div>

      <Panel title="Reward Events">
        {rewardEvents.length === 0 ? <EmptyState message="No reward events yet." /> : (
          <div className="max-h-64 overflow-y-auto eks-scroll space-y-1.5">
            {rewardEvents.map((e) => (
              <div key={e.id} className="flex items-center justify-between text-xs rounded-md border border-border/40 p-2">
                <div className="flex items-center gap-2">
                  {e.type === "reward_ready" || e.type === "reward_triggered" ? (
                    <Gift className="h-3.5 w-3.5 text-[var(--brand)]" />
                  ) : e.type === "reward_cancelled" ? (
                    <AlertCircle className="h-3.5 w-3.5 text-destructive" />
                  ) : (
                    <Coins className="h-3.5 w-3.5 text-muted-foreground" />
                  )}
                  <Mono className="text-[10px]">{e.type}</Mono>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-[10px] text-muted-foreground">rank #{e.rank}</span>
                  <span className="font-medium text-[var(--brand)]">{e.currency} {e.amount.toLocaleString()}</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </Panel>

      <Panel title="Payment Boundary">
        <div className="rounded-md border border-amber-500/30 bg-amber-500/5 p-3">
          <div className="flex items-start gap-2">
            <AlertCircle className="h-4 w-4 text-amber-500 mt-0.5 shrink-0" />
            <div>
              <p className="text-xs font-medium text-amber-700 dark:text-amber-400">No payment logic in competition services</p>
              <p className="text-xs text-muted-foreground mt-1">
                The Competition Engine emits events (Reward Ready, Prize Pool Updated, Measurement Fee Received, Reward Cancelled, Payout Requested).
                The Payment Provider (initially PaySwap) consumes these events and performs all financial operations.
                The provider is fully replaceable — swap PaySwap for Stripe by registering a new provider.
              </p>
            </div>
          </div>
        </div>
      </Panel>
    </div>
  );
}
